# Generated by Django 3.0.3 on 2020-03-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apartments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('img1', models.ImageField(upload_to='pics')),
                ('img2', models.ImageField(upload_to='pics')),
                ('img3', models.ImageField(upload_to='pics')),
                ('img4', models.ImageField(upload_to='pics')),
                ('img5', models.ImageField(upload_to='pics')),
                ('img6', models.ImageField(upload_to='pics')),
                ('img7', models.ImageField(upload_to='pics')),
                ('img8', models.ImageField(upload_to='pics')),

                ('bed', models.IntegerField()),
                ('ter', models.IntegerField()),
                ('sf', models.IntegerField()),
                ('sqfeet', models.BooleanField(default=False)),
                ('sqyard', models.BooleanField(default=False)),
            ],
        ),
    ]
